services:
  mqtt-agent:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mqtt-agent
    restart: always
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /run/systemd/system:/run/systemd/system